-- ============================================================
-- LUMINA LIBRARY — SUPABASE SCHEMA COMPLETO
-- Ejecutar en: Supabase Dashboard > SQL Editor > New Query
-- ============================================================

-- ============================================================
-- 1. TABLA: categories
-- ============================================================
CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 2. TABLA: profiles  (extiende auth.users de Supabase)
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
    id       UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name     TEXT NOT NULL,
    username TEXT UNIQUE,
    role     TEXT NOT NULL DEFAULT 'estudiante'
               CHECK (role IN ('admin', 'profesor', 'estudiante')),
    phone    TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 3. TABLA: books
-- ============================================================
CREATE TABLE IF NOT EXISTS books (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            TEXT NOT NULL,
    author           TEXT NOT NULL,
    category         TEXT REFERENCES categories(name) ON UPDATE CASCADE ON DELETE SET NULL,
    isbn             TEXT UNIQUE,
    cover            TEXT,
    total_copies     INTEGER DEFAULT 1,
    available_copies INTEGER DEFAULT 1,
    penalty_rate     NUMERIC(10,2) DEFAULT 1.00,   -- S/ por día de mora
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 4. TABLA: loans
-- ============================================================
CREATE TABLE IF NOT EXISTS loans (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id             BIGINT REFERENCES books(id) ON DELETE CASCADE,
    user_id             UUID   REFERENCES auth.users ON DELETE CASCADE,
    phone               TEXT,
    request_date        TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    borrow_date         TIMESTAMP WITH TIME ZONE,
    due_date            TIMESTAMP WITH TIME ZONE,
    return_date         TIMESTAMP WITH TIME ZONE,           -- fecha real de devolución
    status              TEXT NOT NULL DEFAULT 'pending_pickup'
                          CHECK (status IN (
                            'pending_pickup',
                            'active',
                            'overdue',
                            'pending_return',
                            'returned'
                          )),
    is_extending        BOOLEAN DEFAULT FALSE,
    extension_requested BOOLEAN DEFAULT FALSE,
    manual_penalty      NUMERIC(10,2) DEFAULT 0,   -- ajuste manual de mora (admin)
    paid_penalty        NUMERIC(10,2) DEFAULT 0,   -- mora cobrada al momento de devolución
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 5. TABLA: reservations
-- ============================================================
CREATE TABLE IF NOT EXISTS reservations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT REFERENCES books(id) ON DELETE CASCADE,
    user_id    UUID   REFERENCES auth.users ON DELETE CASCADE,
    priority   BOOLEAN DEFAULT FALSE,
    date       TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 6. TABLA: held_books  (libro apartado esperando al usuario)
-- ============================================================
CREATE TABLE IF NOT EXISTS held_books (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id       BIGINT REFERENCES books(id) ON DELETE CASCADE,
    user_id       UUID   REFERENCES auth.users ON DELETE CASCADE,
    assigned_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 7. FUNCTION + TRIGGER: crear perfil automáticamente al registrarse
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, username, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name',     'Nuevo Usuario'),
    COALESCE(new.raw_user_meta_data->>'username',  new.email),
    COALESCE(new.raw_user_meta_data->>'role',      'estudiante')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================================
-- 8. ROW LEVEL SECURITY (RLS)
-- ============================================================
ALTER TABLE categories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE books       ENABLE ROW LEVEL SECURITY;
ALTER TABLE loans       ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE held_books  ENABLE ROW LEVEL SECURITY;

-- -------- POLICIES: categories --------
DROP POLICY IF EXISTS "categories_select_all"  ON categories;
DROP POLICY IF EXISTS "categories_admin_write"  ON categories;

-- Cualquier usuario autenticado puede leer categorías
CREATE POLICY "categories_select_all"
  ON categories FOR SELECT
  USING (auth.role() = 'authenticated');

-- Solo admins pueden crear/editar/borrar categorías
CREATE POLICY "categories_admin_write"
  ON categories FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- -------- POLICIES: profiles --------
DROP POLICY IF EXISTS "profiles_select_own"     ON profiles;
DROP POLICY IF EXISTS "profiles_admin_all"      ON profiles;
DROP POLICY IF EXISTS "profiles_update_own"     ON profiles;

-- Cada usuario puede leer su propio perfil
CREATE POLICY "profiles_select_own"
  ON profiles FOR SELECT
  USING (id = auth.uid());

-- Cada usuario puede actualizar su propio perfil (nombre y teléfono)
CREATE POLICY "profiles_update_own"
  ON profiles FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- El admin puede leer y modificar todos los perfiles
CREATE POLICY "profiles_admin_all"
  ON profiles FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- -------- POLICIES: books --------
DROP POLICY IF EXISTS "books_select_all"    ON books;
DROP POLICY IF EXISTS "books_admin_write"   ON books;
DROP POLICY IF EXISTS "books_user_update"   ON books;

-- Todos los autenticados pueden ver los libros
CREATE POLICY "books_select_all"
  ON books FOR SELECT
  USING (auth.role() = 'authenticated');

-- Admin puede crear, actualizar y eliminar libros
CREATE POLICY "books_admin_write"
  ON books FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Usuarios autenticados pueden actualizar available_copies (necesario para préstamos)
CREATE POLICY "books_user_update_copies"
  ON books FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- -------- POLICIES: loans --------
DROP POLICY IF EXISTS "loans_select_own"    ON loans;
DROP POLICY IF EXISTS "loans_insert_own"    ON loans;
DROP POLICY IF EXISTS "loans_update_own"    ON loans;
DROP POLICY IF EXISTS "loans_admin_all"     ON loans;

-- Cada usuario puede ver sus propios préstamos
CREATE POLICY "loans_select_own"
  ON loans FOR SELECT
  USING (user_id = auth.uid());

-- Cada usuario puede crear un préstamo para sí mismo
CREATE POLICY "loans_insert_own"
  ON loans FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Cada usuario puede actualizar sus propios préstamos (ej: solicitar devolución)
CREATE POLICY "loans_update_own"
  ON loans FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Admin puede ver y gestionar todos los préstamos
CREATE POLICY "loans_admin_all"
  ON loans FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- -------- POLICIES: reservations --------
DROP POLICY IF EXISTS "reservations_select_own"  ON reservations;
DROP POLICY IF EXISTS "reservations_insert_own"  ON reservations;
DROP POLICY IF EXISTS "reservations_delete_own"  ON reservations;
DROP POLICY IF EXISTS "reservations_admin_all"   ON reservations;

-- Cada usuario puede ver sus propias reservas
CREATE POLICY "reservations_select_own"
  ON reservations FOR SELECT
  USING (user_id = auth.uid());

-- Cada usuario puede reservar para sí mismo
CREATE POLICY "reservations_insert_own"
  ON reservations FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Cada usuario puede cancelar su propia reserva
CREATE POLICY "reservations_delete_own"
  ON reservations FOR DELETE
  USING (user_id = auth.uid());

-- Admin gestiona todas las reservas
CREATE POLICY "reservations_admin_all"
  ON reservations FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- -------- POLICIES: held_books --------
DROP POLICY IF EXISTS "held_select_own"   ON held_books;
DROP POLICY IF EXISTS "held_admin_all"    ON held_books;

-- Cada usuario puede ver libros apartados para él
CREATE POLICY "held_select_own"
  ON held_books FOR SELECT
  USING (user_id = auth.uid());

-- Admin gestiona todos los held_books
CREATE POLICY "held_admin_all"
  ON held_books FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Usuarios autenticados pueden insertar/eliminar held_books
-- (necesario porque el código del cliente gestiona la cola)
CREATE POLICY "held_auth_insert"
  ON held_books FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "held_auth_delete"
  ON held_books FOR DELETE
  USING (auth.role() = 'authenticated');

-- ============================================================
-- 9. STORAGE: bucket 'book-covers' (portadas de libros)
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('book-covers', 'book-covers', true)
ON CONFLICT (id) DO NOTHING;

-- Acceso público de lectura
DROP POLICY IF EXISTS "book_covers_public_select" ON storage.objects;
CREATE POLICY "book_covers_public_select"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'book-covers');

-- Solo autenticados pueden subir portadas
DROP POLICY IF EXISTS "book_covers_auth_insert" ON storage.objects;
CREATE POLICY "book_covers_auth_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'book-covers' AND auth.role() = 'authenticated');

-- Solo autenticados pueden actualizar portadas
DROP POLICY IF EXISTS "book_covers_auth_update" ON storage.objects;
CREATE POLICY "book_covers_auth_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'book-covers' AND auth.role() = 'authenticated');

-- Solo admins pueden eliminar portadas
DROP POLICY IF EXISTS "book_covers_admin_delete" ON storage.objects;
CREATE POLICY "book_covers_admin_delete"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'book-covers'
    AND EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ============================================================
-- 10. DATOS INICIALES: categorías por defecto
-- ============================================================
INSERT INTO categories (name) VALUES
  ('Literatura'),
  ('Historia'),
  ('Ciencias'),
  ('Tecnología'),
  ('Filosofía'),
  ('Arte'),
  ('Economía'),
  ('Derecho'),
  ('Medicina'),
  ('Educación')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 11. REALTIME: habilitar para tablas que usan subscripciones
-- ============================================================
-- Ejecuta esto en el Dashboard > Database > Replication
-- o descomenta si tu plan lo soporta vía SQL:
/*
ALTER PUBLICATION supabase_realtime ADD TABLE books;
ALTER PUBLICATION supabase_realtime ADD TABLE loans;
ALTER PUBLICATION supabase_realtime ADD TABLE reservations;
ALTER PUBLICATION supabase_realtime ADD TABLE held_books;
ALTER PUBLICATION supabase_realtime ADD TABLE profiles;
*/

-- ============================================================
-- FIN DEL SCHEMA
-- ============================================================
